version: "3.9"

services:
  caddy:
    container_name: caddy
    image: ingtranet/caddy:2.6.4
    restart: always
    environment:
      "ACME_EMAIL": "{{ secret_acme_email }}"
      "CLOUDFLARE_TOKEN": "{{ secret_cloudflare_token }}"
    volumes:
      - type: bind
        source: "{{ config_path }}/{{ item }}/caddy/Caddyfile"
        target: /etc/caddy/Caddyfile
      - type: bind
        source: /volume1/docker/caddy
        target: /data/caddy
    networks:
      vlan365:
        ipv4_address: 10.3.65.11

  seaweedfs:
    container_name: seaweedfs
    image: harbor.ingtra.net/docker.io/chrislusf/seaweedfs:3.59_large_disk
    command: server -master.volumeSizeLimitMB 30720 -volume.max 1000 -options /etc/seaweedfs/options
    restart: always
    volumes:
      - type: bind
        source: /volume1/seaweedfs/config
        target: /etc/seaweedfs
      - type: bind
        source: /volume1/seaweedfs/data
        target: /data
    networks:
      vlan365:
        ipv4_address: 10.3.65.12

  victoria-metrics:
    container_name: victoria-metrics
    image: harbor.ingtra.net/docker.io/victoriametrics/victoria-metrics:v1.93.10
    restart: always
    volumes:
      - type: bind
        source: /volume1/docker/victoria-metrics/data
        target: /victoria-metrics-data
    networks:
      vlan365:
        ipv4_address: 10.3.65.13

  postgresql:
    container_name: postgresql
    image: harbor.ingtra.net/docker.io/library/postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: "{{ secret_postgresql_password }}"
      POSTGRES_INITDB_ARGS: "-E UTF8"
    volumes:
      - type: bind
        source: /volume1/docker/postgresql/data
        target: /var/lib/postgresql/data
      - type: bind
        source: /volume1/docker/postgresql/conf/postgresql.conf
        target: /etc/postgresql/postgresql.conf
    networks:
      vlan365:
        ipv4_address: 10.3.65.14

networks:
  vlan365:
    name: vlan365
    driver: macvlan
    driver_opts:
      parent: ovs_vlan365
    ipam:
      config:
        - subnet: 10.3.65.0/24
          ip_range: 10.3.65.0/24
          gateway: 10.3.65.1