version: "3.9"

services:
  caddy:
    container_name: caddy
    image: ingtranet/caddy:2.6.4
    restart: always
    environment:
      "ACME_EMAIL": "{{ secret_acme_email }}"
      "CLOUDFLARE_TOKEN": "{{ secret_cloudflare_token }}"
    volumes:
      - type: bind
        source: "{{ config_path }}/{{ item }}/caddy/Caddyfile"
        target: /etc/caddy/Caddyfile
      - type: bind
        source: /volume1/docker/caddy
        target: /data/caddy
    networks:
      vlan365:
        ipv4_address: 10.3.65.11

  seaweedfs:
    container_name: seaweedfs
    image: chrislusf/seaweedfs:3.59_large_disk
    command: server -master.volumeSizeLimitMB 30720 -volume.max 1000 -options /etc/seaweedfs/options
    restart: always
    volumes:
      - type: bind
        source: /volume1/seaweedfs/config
        target: /etc/seaweedfs
      - type: bind
        source: /volume1/seaweedfs/data
        target: /data
    networks:
      vlan365:
        ipv4_address: 10.3.65.12

networks:
  vlan365:
    name: vlan365
    driver: macvlan
    driver_opts:
      parent: ovs_vlan365
    ipam:
      config:
        - subnet: 10.3.65.0/24
          ip_range: 10.3.65.0/24
          gateway: 10.3.65.1