k0s:
  hosts:
    k8s-na-ctrl-1.vd.ingtra.net:
      role: controlplane
    k8s-na-work-1.vd.ingtra.net:
      role: worker
    k8s-na-work-2.vd.ingtra.net:
      role: worker
    orin-nx-1.dv.ingtra.net:
      ansible_user: ing
      role: worker
      containerd_profiles:
        - default
        - nvidia
    orin-nx-2.dv.ingtra.net:
      ansible_user: ing
      role: worker
      containerd_profiles:
        - default
        - nvidia
    orin-nx-3.dv.ingtra.net:
      ansible_user: ing
      role: worker
      containerd_profiles:
        - default
        - nvidia
    # k8s-ga-gpu-1.vd.ingtra.net:
    #   ansible_user: ing
    #   role: worker
    #   containerd_profiles:
    #     - default
    #     - nvidia
  vars:
    k0s_version: v1.29.7+k0s.0
    node_type: default
    containerd_profiles:
      - default
    force_reinstall: false
    token_issuer: k8s-na-ctrl-1.vd.ingtra.net