k0s:
  hosts:
    "k0s-controlplane.vd.ingtra.net":
      role: controlplane
    "k0s-worker-x86-1.vd.ingtra.net":
      role: worker
      node_type: default
  vars:
    k0s_version: v1.27.1+k0s.0
    node_type: default
    containerd_profile: default
    force_reinstall: false
    token_issuer: k0s-controlplane.vd.ingtra.net