tailscale:
  hosts:
    "tailscale-home.vd.ingtra.net":
      role: router
      additionalConfigs:
        advertise-routes: 10.0.0.0/16,10.1.0.0/16,10.2.0.0/16,10.3.0.0/16,10.255.10.0/24
        snat-subnet-routes: false
        accept-routes: true
  vars:
    additionalConfigs: {}
