apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
spec:
  api:
    address: {{ ansible_eth0.ipv4.address }}
    sans:
      - 10.160.0.1
      - {{ ansible_eth0.ipv4.address }}
      - {{ inventory_hostname }}
      - k8s-ga-api.hp.ingtra.net
  extensions:
    helm:
      charts:
        - name: argocd
          chartname: argo/argo-cd
          version: 6.5.1
          namespace: argocd
          values: |
            server:
              extraArgs:
              - --insecure
      repositories:
        - name: argo
          url: https://argoproj.github.io/argo-helm
  network:
    provider: calico
    clusterDomain: kg.ingtra.net
    podCIDR: 10.160.32.0/19
    serviceCIDR: 10.160.0.0/19
  storage:
    type: etcd
  workerProfiles:
    - name: default
      values:
        shutdowngraceperiod: 300s
        shutdownGracePeriodCriticalPods: 60s
  featureGates:
    - name: GracefulNodeShutdown
      enabled: true
      components: ["kubelet"]