- name: Copy cluster config
  ansible.builtin.template:
    src: cluster_config.yaml
    dest: /etc/k0s/k0s.yaml

- name: Install Controlplane
  ansible.builtin.shell:
    cmd: sudo /usr/local/bin/k0s install controller -c /etc/k0s/k0s.yaml
    creates: /etc/systemd/system/k0scontroller.service

- name: Start Controlplane
  ansible.builtin.shell:
    cmd: |
      set -ex
      if [ ! -f "/etc/k0s/k0s.yaml.md5" ] || [ $(md5sum /etc/k0s/k0s.yaml) -neq $(cat /etc/k0s/k0s.yaml.md5) ]; then
        sudo systemctl stop k0scontroller || true
        sudo /usr/local/bin/k0s install controller -c /etc/k0s/k0s.yaml --force
      fi
      sudo systemctl start k0scontroller
      md5sum /etc/k0s/k0s.yaml > /etc/k0s/k0s.yaml.md5

- name: Create join token
  ansible.builtin.shell:
    cmd: sudo /usr/local/bin/k0s && sleep 10 && sudo /usr/local/bin/k0s token create --role=worker > /etc/k0s/worker_join_token
    creates: /etc/k0s/worker_join_token
  when: inventory_hostname == token_issuer
  register: create_token
  until: create_token is not failed
  retries: 10
  delay: 20

- name: Register join token
  ansible.builtin.shell:
    cmd: sudo cat /etc/k0s/worker_join_token
  register: worker_join_token
  when: inventory_hostname == token_issuer