- name: Start Worker
  community.docker.docker_container:
    name: k0s-worker
    hostname: "{{ k0s_hostname }}"
    image: harbor.ingtra.net/docker.io/ingtranet/k0s:v1.27.1-k0s.0-l4t-r35.1.0
    pull: true
    env:
      NVIDIA_VISIBLE_DEVICES: all
      DNS_SERVER: 10.0.32.11
    command: k0s worker {{ hostvars[token_issuer]['worker_join_token']['stdout'] }}
    privileged: true
    cgroupns_mode: host
    runtime: nvidia
    networks:
      - name: vlan234
        ipv4_address: "{{ k0s_ip_address }}"
    dns_servers:
      - "10.0.32.11"
    dns_search_domains:
      - vd.ingtra.net
    restart_policy: always
    detach: true
    volumes:
      - "/etc/k0s:/etc/k0s"
      - "/var/lib/k0s:/var/lib/k0s"
      #- "/usr/bin/nvidia-container-runtime:/usr/bin/nvidia-container-runtime"
    state: started

