- name: Start Worker
  community.docker.docker_container:
    name: k0s-worker
    hostname: "{{ inventory_hostname_short }}"
    image: harbor.ingtra.net/docker.io/k0sproject/k0s:{{ k0s_version.replace('+', '-') }}
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        sed -e 's/127.0.0.11/10.0.32.11/g' /etc/resolv.conf | tee /etc/resolv.conf && \
        exec /sbin/tini -- /bin/sh /entrypoint.sh k0s worker {{ hostvars[token_issuer]['worker_join_token']['stdout'] }}
    privileged: true
    cgroupns_mode: host
    networks:
      - name: vlan234
        ipv4_address: 10.2.34.111
    dns_servers:
      - "10.0.32.11"
    dns_search_domains:
      - vd.ingtra.net
    restart_policy: always
    detach: true
    volumes:
      - "/etc/k0s:/etc/k0s"
      - "/var/lib/k0s:/var/lib/k0s"
    state: started

