- name: Copy cluster config
  ansible.builtin.template:
    src: cluster_config.yaml
    dest: /etc/k0s/k0s.yaml

- name: Install Controlplane
  ansible.builtin.shell:
    cmd: sudo /usr/local/bin/k0s install controller -c /etc/k0s/k0s.yaml
    creates: /etc/systemd/system/k0scontroller.service

- name: Start Controlplane
  ansible.builtin.shell:
    cmd: |
      set -ex
      if [ ! -f "/etc/k0s/k0s.yaml.md5" ] || [ $(md5sum /etc/k0s/k0s.yaml) -neq $(cat /etc/k0s/k0s.yaml.md5) ]; then
        sudo systemctl stop k0scontroller || true
      fi
      sudo systemctl start k0scontroller
      md5sum /etc/k0s/k0s.yaml > /etc/k0s/k0s.yaml.md5

- name: Create join token
  ansible.builtin.shell:
    cmd: sudo /usr/local/bin/k0s token create --role=worker --expiry=1h
  register: join_token
  when: inventory_hostname == token_issuer
  until: "join_token is not failed"
  retries: 10
  delay: 30