- name: Create /etc/k0s
  ansible.builtin.file:
    path: /etc/k0s/containerd.d
    state: directory

- name: Copy containerd import config
  ansible.builtin.copy:
    src: containerd/{{ item }}.toml
    dest: //etc/k0s/containerd.d/{{ item }}.toml
  loop: "{{ containerd_profiles }}"

- name: Disable NetworkManager for calico
  ansible.builtin.copy:
    src: calico.conf
    dest: /etc/NetworkManager/conf.d/calico.conf

- name: Reload NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Install K0S
  ansible.builtin.include_tasks: install_{{ node_type }}_k0s.yml

- name: Install controlplane
  ansible.builtin.include_tasks: install_{{ node_type }}_controlplane.yml
  when: role == 'controlplane'

- name: Install worker
  ansible.builtin.include_tasks: install_{{ node_type }}_worker.yml
  when: role == 'worker'