- name: Make config
  ansible.builtin.template:
    src: vyos.boot
    dest: /tmp/ansible-vyos.boot

- name: Copy file
  ansible.netcommon.net_put:
    src: /tmp/ansible-vyos.boot
    protocol: sftp
    dest: /tmp/ansible-vyos.boot

- name: Apply config
  vyos.vyos.vyos_command:
    commands:
      - configure
      - load /tmp/ansible-vyos.boot
      - commit
      - save
