- name: Install avahi
  ansible.builtin.dnf:
    name:
      - epel-release
    state: present

- name: Install avahi
  ansible.builtin.dnf:
    name:
      - avahi
      - nss-mdns
    state: latest

- name: Copy avahi-daemon.conf
  ansible.builtin.copy:
    src: avahi-daemon.conf
    dest: /etc/avahi/avahi-daemon.conf

- name: Reload avahi
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: true
    state: reloaded