- name: Install docker python client
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_system_vendor != "Synology Inc."

- name: Create config path
  ansible.builtin.file:
    path: "{{ config_path }}/{{ item }}"
    state: directory
  loop: "{{ compose_roles }}"

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ config_path }}/{{ item }}/"
  loop: "{{ compose_roles }}"

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "{{ item }}/docker-compose.yml"
    dest: "{{ config_path }}/{{ item }}/docker-compose.yml"
  loop: "{{ compose_roles }}"

- name: Docker compose up
  community.docker.docker_compose:
    project_src: "{{ config_path }}/{{ item }}"
  loop: "{{ compose_roles }}"