- name: Import Crate RPM Key
  ansible.builtin.rpm_key:
    state: present
    key: https://cdn.crate.io/downloads/yum/RPM-GPG-KEY-crate

- name: Install CrateDB Repo
  ansible.builtin.yum:
    name: https://cdn.crate.io/downloads/yum/7/x86_64/crate-release-7.0-1.x86_64.rpm
    state: present

- name: Install CrateDB
  ansible.builtin.yum:
    name: crate
    state: present

- name: Create Log Directory
  ansible.builtin.file:
    path: /var/log/crate
    group: crate
    owner: crate
    state: directory

- name: Create Data Directory
  ansible.builtin.file:
    path: /data/crate
    group: crate
    owner: crate
    state: directory

- name: Copy Crate Config
  ansible.builtin.template:
    src: crate.yml.j2
    dest: /etc/crate/crate.yml
    group: crate
    owner: crate

- name: Copy Crate ENV
  ansible.builtin.template:
    src: crate.env.j2
    dest: /etc/sysconfig/crate
    group: root
    owner: root

- name: Start CrateDB 
  ansible.builtin.systemd:
    name: crate
    enabled: yes
    daemon_reload: yes
    state: restarted