- name: For centos
  ansible.builtin.import_tasks: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

- name: Install python
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

- name: Install python
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install docker python client
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
      - requests<2.32
    state: present

- name: Start docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started