- name: For centos
  ansible.builtin.import_tasks: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

- name: Install pip
  ansible.builtin.shell:
    cmd: python3 -m ensurepip --upgrade

- name: Install docker python client
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
    state: present