- name: Create headscale group
  ansible.builtin.group:
    name: headscale
    system: true

- name: Create headscale user
  ansible.builtin.user:
    name: headscale
    system: true
    shell: /usr/bin/nologin
    groups:
      - headscale

- name: Install headscale
  ansible.builtin.get_url:
    url: https://github.com/juanfont/headscale/releases/download/v{{ headscale_version }}/headscale_{{ headscale_version }}_linux_amd64
    dest: /usr/local/bin/headscale
    mode: 0755

- name: Create /etc/headscale
  ansible.builtin.file:
    path: /etc/headscale
    state: directory
    owner: headscale
    group: headscale

- name: Copy config file
  ansible.builtin.copy:
    src: config.yaml
    dest: /etc/headscale/config.yaml
    owner: headscale
    group: headscale 

- name: Create /var/lib/headscale
  ansible.builtin.file:
    path: /var/lib/headscale
    state: directory
    owner: headscale
    group: headscale

- name: Create SQLite file
  ansible.builtin.file:
    path: /var/lib/headscale/db.sqlite
    state: touch
    owner: headscale
    group: headscale

- name: Copy tls.crt
  ansible.builtin.copy:
    src: secret-tls.crt
    dest: /var/lib/headscale/tls.crt
    owner: headscale
    group: headscale 

- name: Copy tls.key
  ansible.builtin.copy:
    src: secret-tls.key
    dest: /var/lib/headscale/tls.key
    owner: headscale
    group: headscale 

- name: Create /var/run/headscale
  ansible.builtin.file:
    path: /var/run/headscale
    state: directory
    owner: headscale
    group: headscale

- name: Link /var/run/headscale/headscale.sock
  ansible.builtin.file:
    src: /var/run/headscale/headscale.sock
    path: /var/run/headscale.sock
    state: link
    force: yes
    owner: headscale
    group: headscale

- name: Create SystemD service
  ansible.builtin.copy:
    src: headscale.service
    dest: /etc/systemd/system/headscale.service

- name: Start and enable service
  ansible.builtin.systemd:
    daemon_reload: true
    name: headscale
    enabled: true
    state: restarted

- name: Allow all access to https
  ansible.posix.firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled